name: lint

on:
  pull_request:
    branches: [ 'main' ]

jobs:
  lint:
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Check out repository'
        uses: actions/checkout@v4
      - name: 'Install markdownlint-cli'
        run: npm install -g markdownlint-cli
      - name: 'Lint markdown files'
        run: markdownlint '**/*.md'